language: java
# install: ant deps
sudo: require

before_install:
  - java -version

script:
  - jdk_switcher use oraclejdk8
  # - ./build_processing.sh
  - cd SuperBar; chmod -x download_processing.sh; ./download_processing.sh; chmod -x build.sh; ./build.sh
  - cd ..
  - cd SuperBarMobile; chmod -x download_processing.sh; ./download_processing.sh; chmod -x build.sh; ./build.sh
  - cd ..

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
