language: java
sudo: required
# install: ant deps

before_install:
  - java -version

script:
  - jdk_switcher use oraclejdk8
  # - ./build_processing.sh
  - sudo ./SuperBar/download_processing.sh
  - sudo ./SuperBar/build.sh
  - sudo ./SuperBarMobile/download_processing.sh
  - sudo ./SuperBarMobile/build.sh

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
