language: java
# install: ant deps
sudo: require

before_install:
  - java -version

script:
  - jdk_switcher use oraclejdk8
  # - ./build_processing.sh
  - cd SuperBar
  - ./download_processing.sh
  - ./build.sh
  - cd ../SuperBarMobile
  - ./download_processing.sh
  - ./build.sh

after_failure:
  - find . | egrep "processing-java"

after_success:
  - find . | egrep "processing-java"
